---
title: "SISBID Module 2: Your Turn: Katz Mouse"
author: "Di Cook"
date: "July 8-10, 2015"
output: html_document
---

```{r dataread, cache=FALSE, warning=FALSE, error=FALSE, message=FALSE}
# Load the data 
load("katz_mouse_eset.RData")
str(katz.mouse.eset)

library(Biobase)
katz.count.table <- exprs(katz.mouse.eset)
dim(katz.count.table)
head(katz.count.table)
colnames(katz.count.table) <- c("CUGBP1.1", "CONTROL.1", "CUGBP1.2", "CONTROL.2")

counts.df <- data.frame(katz.count.table[,c(1,3,2,4)])

# Filter weakly expressed
cpms = cpm(counts.df)
counts.all <- counts.df
keep = rowSums(cpms > 1) >= 2 
counts.df = counts.all[keep,]
dim(counts.all); dim(counts.df)
```

```{r norm, cache=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(ggplot2)
library(GGally)
d = DGEList(counts = counts.df, group = c("CUGBP1", "CUGBP1", "CONTROL", "CONTROL"))
str(d)
d = calcNormFactors(d)
str(d)
d$samples
par(pty="s")
d.mds <- plotMDS(d, labels = colnames(counts.df),
       gene.selection = "common", xlim=c(-1.9, 1.9))

d$counts <- data.frame(d$counts) # Needs to be a data frame
d$lcounts <- log(d$counts+1)
ggparcoord(d$lcounts, columns=1:4, boxplot=TRUE, scale="globalminmax", 
           showPoints=FALSE, alphaLines=0) + 
  xlab("") + ylab("log(cpm)") + 
  theme_bw()

# Use trimmed mean normalization
d = calcNormFactors(d, method="TMM")
nc = data.frame(cpm(d, normalized.lib.sizes = TRUE, log=TRUE))
ggparcoord(nc, columns=1:4, boxplot=TRUE, scale="globalminmax", showPoints=FALSE,
           alphaLines=0) + 
  xlab("") + ylab("log(cpm)") + 
  theme_bw()

d.mds2 <- plotMDS(nc, labels = colnames(counts.df),
       gene.selection = "common", xlim=c(-2.9, 2.9))
```

```{r mvplots, cache=FALSE, warning=FALSE, error=FALSE, message=FALSE}
# Scatterplot matrix of normalized data
ggscatmat(nc)

# Full parallel coordinate plot
ggparcoord(nc, columns=1:4, scale="globalminmax", alphaLines=0.5) + 
  xlab("") + ylab("log(cpm)") + 
  theme_bw()
ggparcoord(nc, columns=1:4, scale="globalminmax", alphaLines=0.01) + 
  xlab("") + ylab("log(cpm)") + 
  theme_bw()

# Porcupine plot
ggplot(nc) + 
  geom_segment(aes(x=CUGBP1.1, xend=CUGBP1.2, y=CONTROL.1, yend=CONTROL.2)) +
  xlab("CUGBP") + ylab("CTRL") +
  theme_bw() + theme(aspect.ratio=1)
```

```{r dispersion, cache=FALSE, warning=FALSE, error=FALSE, message=FALSE}
# Check the mean and variance relationship
# For the Poisson model, the mean = variance 
# RNA seq tends to be more overdispersed, variance is larger than expected
# Over-dispersed leads to fitting a negative binomial model
# Common dispersion would be used if all genes assumed to have same variance
d = estimateCommonDisp(d)
d$common.dispersion
# Tagwise dispersion is a weighted average of individual gene dispersion 
# with common dispersion
d = estimateTagwiseDisp(d)
summary(d$tagwise.dispersion)
d$prior.n

# Examine the dispersions, in relation to the means
mv <- binMeanVar(d, group = d$samples$group)
# $means are the means for each gene
# $vars are the pooled variances for each gene
qplot(mv$means[mv$vars>5], mv$vars[mv$vars>5], alpha=I(0.5)) + 
  scale_x_log10() + scale_y_log10() + 
  geom_smooth(method="lm") + theme_bw() + theme(aspect.ratio=1)
qplot(mv$vars[mv$vars>5], d$tagwise.dispersion[mv$vars>5]) + 
  scale_x_log10() + scale_y_log10() +
  geom_smooth() + theme_bw() + theme(aspect.ratio=1)
```

```{r sig, cache=FALSE, warning=FALSE, error=FALSE, message=FALSE}
# Test for differential expression (‘classic’ edgeR)
de = exactTest(d, pair = c("CUGBP1","CONTROL"))
tt = topTags(de, n = nrow(d), sort.by="none")
nc.sig <- data.frame(gene=rownames(nc), nc, tt)
nc.sig$sig05 <- ifelse(nc.sig$FDR < 0.05, "S", "NS")
nc.sig$sig01 <- ifelse(nc.sig$FDR < 0.01, "S", "NS")
nc.sig$sig005 <- ifelse(nc.sig$FDR < 0.005, "S", "NS")

# Porcupine plot with significance
ggplot(nc.sig) + geom_segment(aes(x=CUGBP1.1, xend=CUGBP1.2, y=CONTROL.1, 
                                  yend=CONTROL.2, color=sig05)) +
  scale_color_manual(values=c("S"="red", "NS"="grey90")) + 
  xlab("CUGBP") + ylab("CONTROL") +
  theme_bw() + theme(aspect.ratio=1)
```

```{r interaction, cache=FALSE, warning=FALSE, error=FALSE, message=FALSE}
# Interaction plots of top genes
library(tidyr)
library(dplyr)
nc.sig <- arrange(nc.sig, PValue)
g1 <- gather(nc.sig[1,2:5])
g1$trt <- substr(g1$key, 1, 6)
g1.mean <- summarise(group_by(g1, trt), m=mean(value))
qplot(trt, value, data=g1, xlab="Treatment", ylab="logCPM", 
      size=I(5), alpha=I(0.5)) +
  annotate("segment", x=1, xend=2, y=g1.mean$m[1], 
           yend=g1.mean$m[2], colour="grey80") + 
  ggtitle(nc.sig$gene[1]) +
  theme_bw() + theme(aspect.ratio=1)
g1 <- gather(nc.sig[380,2:5])
g1$trt <- substr(g1$key, 1, 6)
g1.mean <- summarise(group_by(g1, trt), m=mean(value))
qplot(trt, value, data=g1, xlab="Treatment", ylab="logCPM", 
      size=I(5), alpha=I(0.5)) +
  annotate("segment", x=1, xend=2, y=g1.mean$m[1], 
           yend=g1.mean$m[2], colour="grey80") + 
  ggtitle(nc.sig$gene[1]) +
  theme_bw() + theme(aspect.ratio=1)
```

```{r vischeck, cache=FALSE, warning=FALSE, error=FALSE, message=FALSE}
# To check the effect size, visually, we are going to scramble the 
# labels, and re-run the significance testing
dp <- d
ncp <- nc
dp$samples$group <- c("CONTROL","CUGBP1","CUGBP1","CONTROL")
dp$samples$group
dep = exactTest(dp, pair = c("CONTROL","CUGBP1"))
ttp = topTags(dep, n = nrow(dp), sort.by="none")
ncp.sig <- data.frame(gene=rownames(ncp), ncp, ttp)
ncp.sig <- arrange(ncp.sig, PValue)
g1 <- gather(ncp.sig[1,2:5])
g1$trt <- dp$samples$group
g1.mean <- summarise(group_by(g1, trt), m=mean(value))
qplot(trt, value, data=g1, xlab="Treatment", ylab="logCPM",  
      size=I(5), alpha=I(0.5)) +
  annotate("segment", x=1, xend=2, y=g1.mean$m[1], 
           yend=g1.mean$m[2], colour="grey80") + 
  ggtitle(ncp.sig$gene[1]) +
  theme_bw() + theme(aspect.ratio=1)
```